name: Install Atomic Red Team Atomics Folder

on: [push]

jobs:
  install-atomics:
    runs-on: windows-latest
    name: Install Atomic Red Team Atomics Folder

    steps:
    - uses: actions/checkout@v2

    - name: Install Atomic Red Team Atomics Folder
      shell: pwsh
      run: |
        IEX (Invoke-WebRequest 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicsfolder.ps1' -UseBasicParsing);
        Install-AtomicsFolder

